name: Automated API tests
 
on: push 
 
jobs:
  build:
    runs-on: windows-latest 
 
    strategy:
      matrix:
        node-version: [16.x]       
 
    steps:
      - uses: actions/checkout@v3 

      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
       
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra 
 
      - name: Make Directory for Test Results
        run: mkdir -p testArtifacts 
 
      - name: Run Postman Collection        
        run: | 
         newman  run https://api.getpostman.com/collections/21956495-4ba35fa3-9dbc-4dcf-a3d0-bcc23076271b?apikey={{secrets.POSTMAN_API_KEY}} -e https://api.getpostman.com/environments/21956495-ab76680b-50c6-4a3d-88ee-6049fa95d27e?apikey={{secrets.POSTMAN_API_KEY}} --suppress-exit-code -r htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html 

      - name: Output the results
        uses: actions/upload-artifact@v3
        with:
         name: Reports
         path: testArtifacts
