name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install newman
        run: |
         npm install -g newman   
         npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Run POSTMAN collection
        run: |
          newman run ReqRes.postman_collection.json -e qa.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

